### ISSUE TITLE
Incorrect path to files when the docker working directory is not the same as VScode workspace root

### ISSUE THREAD

**Issue by court-jus** [kolofordjango/kolo#11]
Here is the context:

* VSCode is opening the `approot` directory
* The `.kolo` folder is located in `approot/djangoapp/.kolo`
* Docker working directory is `/approot/djangoapp` (volume is set to `.:/approot` in `docker-compose.yml`)
* Setting the `kolo.pathToKoloDirectory` to `djangoapp` works correctly for kolo to find its database within VSCode

But here is the issue:

When inspecting a SQL query, the path to python file that launched the query is relative to `approot/djangoapp` (say the file is `approot/djangoapp/folder1/file1.py`, the SQL trace is marked as being attached to `folder1/file1.py`) and when clicking it, VSCode does not find it because it looks at `approot/folder1/file1.py` instead of `approot/djangoapp/folder1/file1.py`.

Suggested approach:

Allow specifying a prefix for file links or manually setting the "VSCode root".

**Comment by wilhelmklopp** [comment]
👋 @court-jus thanks for opening this and for providing all the context, really appreciate it 🙌 

I think I found the bug that was causing this and just released a fix in version 1.9.1 of the Kolo VSCode extension.

Clicking on the source of SQL queries should now take you to the right place based on your existing `kolo.pathToKoloDirectory` setting.

Let me know if it's still not working :)

**Comment by court-jus** [comment]
It does work :+1:
