### ISSUE TITLE
deocde中没有对错误进行处理

### ISSUE THREAD

**Issue by coding-today** [kolofordjango/kolo#13]
hello, 我在使用kolo遇到以下错误：
'utf-8' codec can't decode byte 0x8f in position 22: invalid start byte
报错是在
<img width="827" alt="image" src="https://user-images.githubusercontent.com/40829761/158548547-e772ea57-ed5f-4648-9895-6d8de9d33bb3.png">

我认为应该在decode函数中加上errors='ignore', 因为默认errors='strict'会触发这个异常（当response.charset=utf-8和content为字节时）。

**Comment by wilhelmklopp** [comment]
The fix for this is included in version 1.4.0 of kolo 🎉 https://pypi.org/project/kolo/

**Comment by coding-today** [comment]
👍
