### ISSUE TITLE
Kolo breaks form flow

### ISSUE THREAD

**Issue by Real-Gecko** [kolofordjango/kolo#15]
I have the following mixin:
```python
class UpdateReadonlyFieldsFormMixin:
    """Use to make form fields uneditable on update.
    Define desired fields in Form.Meta.update_readonly_fields:
    ```
    class Meta:
        update_readonly_fields = ['username', 'email']
    ```
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        instance = getattr(self, "instance", None)

        if instance and instance.id:
            if self.Meta.update_readonly_fields == "__all__":
                field_list = self.fields
            else:
                field_list = self.Meta.update_readonly_fields

            for field in field_list:
                self.fields[field].disabled = True
```
and use it with the form like this:
```python
class OfficeForm(UpdateReadonlyFieldsFormMixin, forms.ModelForm):
    class Meta:
        model = Office
        fields = ["company", "telephone", "work_start_time", "work_ending_time"]
        update_readonly_fields = ["company"]
```
`company` is a required field on `Office` model, but with aforementioned mixin I can make it not editable in `EditView`.
Whenever I enable Kolo middleware flow of the form starts to break. Right after `__init__` is called on a form it gets validated and marks `company` field as required by populating `form._errors` dictionary. I guess that happens because Kolo tries to get the value of `is_valid` which calls clean and causes validation right after `__init__`.

**Comment by Ian-Foote** [comment]
@Real-Gecko Can you give me some more detail? Are you seeing a traceback? Can you share your view code?

I've tried replicating this myself in a test, but I haven't seen a problem.

**Comment by Real-Gecko** [comment]
Trying to reproduce it outside of my current project to pinpoint the exact location of this happening.

**Comment by Real-Gecko** [comment]
I've create a test project repository https://github.com/Real-Gecko/kolo-test.
Take a look at `patches.py` in `proj` folder.
That's the place where I monkey patch `BaseForm.__init__` method. I guess Kolo tries to read some data after this function is executed and that leads to form validation right after `__init__`:
![image](https://user-images.githubusercontent.com/2231969/163248052-41530985-bc11-4229-bf6d-ea4389dcc92b.png)
If you go to office edit view you'll see that field `company` is not editable. You hit save and everything works normally. But as soon as you enable `KoloMiddleware` in `settings.py` it starts to fail:
![image](https://user-images.githubusercontent.com/2231969/163248503-cbc7b06a-ec3c-49eb-b32f-8e7086414e8c.png)

**Comment by Ian-Foote** [comment]
Hi @Real-Gecko.

As a workaround, you can create a `.kolo/config.toml` file with the following contents:

```toml
[filters]
ignore_frames = ["proj/patches.py"]
```

**Comment by Real-Gecko** [comment]
Will try that, thanks for advice.

**Comment by Real-Gecko** [comment]
That worked like a charm, thank you!

**Comment by Ian-Foote** [comment]
I also have a potential long term fix that may land in the next version.

**Comment by Real-Gecko** [comment]
Because I've encountered this again but on another form now, yet another FormMixin :D

**Comment by Ian-Foote** [comment]
Try something like:

```toml
[filters]
ignore_frames = [{callable = "dotted.path.to.callable"}]
```

**Comment by Ian-Foote** [comment]
You can define a custom "filter" that you can refer to in `config.toml`. This filter should return `True` if the frame should be ignored and `False` otherwise:

```python
def my_filter(frame, event, arg) -> bool:
    filepath = frame.f_code.co_filename
    callable_name = frame.f_code.co_name
    if filename_matches(filepath) and function_matches(callable_name):
        return True  # Ignore this frame
    return False  # Process this frame
```

```toml
[filters]
ignore_frames = [{ callable = "path.to.my_filter" }]
```

`filename_matches` and `function_matches` should be replaced with code that implements the appropriate logic.

There's also bunch more stuff available on the `frame` object you could use: https://docs.python.org/3/library/inspect.html#types-and-members

You can probably ignore the `event` and `arg` arguments.

**Comment by Real-Gecko** [comment]
Will try that too.

**Comment by Ian-Foote** [comment]
> I also have a potential long term fix that may land in the next version.

This got merged, so will be in the next release.

**Comment by Real-Gecko** [comment]
OK, I've ended up with simply adding my `mixins.py` to `ignore_frames` and it works now:
```toml
[filters]
ignore_frames = ["proj/patches.py", "common/forms/mixins.py"]
```
And it works like a charm, thanks for your help.

**Comment by wilhelmklopp** [comment]
> This got merged, so will be in the next release.

next release is out now (1.4.0) 🎉 https://pypi.org/project/kolo/

**Comment by Real-Gecko** [comment]
Version 1.4.0 definitely solves the issue, now everything works even without `ignore_frames`. Thanks a lot!
