### ISSUE TITLE
Can't see frames and Variables

### ISSUE THREAD

**Issue by gibosky-voetranquilo** [kolofordjango/kolo#19]
Hi. I started using kolo for debugging bt i'm having problem with frames and variables.

I'm using a local branch of my django project and is been built with Docker. Did add the middleware and added the kolo install for docker yml command arg.

Screenshots:

Frame

![image](https://user-images.githubusercontent.com/91886395/164294218-aed92e35-2a39-472e-9429-ab642587c768.png)

Code - No variables

![image](https://user-images.githubusercontent.com/91886395/164293854-eac69030-8e9f-4cbe-a271-8e9c5a417920.png)

Thanks

**Comment by wilhelmklopp** [comment]
@gibosky-voetranquilo hey! Thanks for opening this issue and for the screenshots. It looks like in your selected trace (`POST .../saveAddress/`), there's just a single frame – I imagine that's why the visualisation isn't showing anything. The visualisation tends to be most useful when you have lots of frames.

In terms of the inline variables, I'm not too sure what's going on: The function that's showing in the screenshot, is it returning on that line 604? If so, the inline codelens should definitely be showing up just above that line – so that's very odd! Are you seeing any errors in the developer tools? You can open them via "Help" -> "Toggle Developer Tools"?

**Comment by wilhelmklopp** [comment]
Oh and are you seeing an inline annotation just above the function definition of `save_address` on line 563?

**Comment by gibosky-voetranquilo** [comment]
Hi. Thanks for the reply.

So for the frame doesn't load for 1 or 32 as show below:

![image](https://user-images.githubusercontent.com/91886395/165087995-9cf00fc7-f295-4762-8e01-ec9a4e179f1a.png)

About the inline annotation, is not showing as per the image below

![image](https://user-images.githubusercontent.com/91886395/165090262-95081625-e324-45cb-91a1-5f9e2c4a25f0.png)

I don't know if there is any relation, but i use git lens and it also have inline annotation (line 79) 

Log from developers tools when i try to load the frame view:

main.js:formatted:8471 Uncaught TypeError: Cannot read properties of null (reading 'call_frame_id')
    at main.js:formatted:8471:61
    at props.frame.frameSpans (main.js:formatted:8475:22)
    at main.js:formatted:8497:18
    at main.js:formatted:8517:6
    at main.js:formatted:8519:2
(anonymous) @ main.js:formatted:8471
props.frame.frameSpans @ main.js:formatted:8475
(anonymous) @ main.js:formatted:8497
(anonymous) @ main.js:formatted:8517
(anonymous) @ main.js:formatted:8519

**Comment by wilhelmklopp** [comment]
@gibosky-voetranquilo appreciate the additional context, super helpful!

Someone actually ran into a similar error message over on our Discord (https://kolo.app/discord) and it looks like being on the lates version of both the kolo python package and the kolo vscode extension resolved this issue for them.

So I wanted to check what versions you are on?
Latest kolo python package release as of today is `1.4.0`
Latest kolo vscode extension release of today is `1.17.2`

**Comment by wilhelmklopp** [comment]
@gibosky-voetranquilo I released 1.17.3 of the VSCode extension yesterday, which should fix a bug that was potentially preventing the visualisation from loading for you. Let me know if the visualisation is working for you now 😄

**Comment by wilhelmklopp** [comment]
@gibosky-voetranquilo 👋 We've made a number of improvements since you originally opened this issue in April. Are you still seeing these errors on the latest kolo vscode extension (1.20.1) and kolo python package (1.7.0) ?
