### ISSUE TITLE
Clear Button for the Requests

### ISSUE THREAD

**Issue by pinguin999** [kolofordjango/kolo#21]
I have a lot of requests and it would be nice the hove a button to clear the request history.

**Comment by wilhelmklopp** [comment]
👋 Thanks for opening this issue @pinguin999 

I'm looking into adding a way to clear all requests

Just to help me better understand: why are you looking to have this feature, what would it help you accomplish?

Thanks!

**Comment by pinguin999** [comment]
If I'm debugging a series of request it's helpful to start with a clear list of request.
And also after a fix I don't want to see old failed request.

**Comment by wilhelmklopp** [comment]
That's super helpful @pinguin999 – so it's very much about visually getting a "clean slate" so that you can focus and don't get distracted by the past. Thank you!

**Comment by LilyFoote** [comment]
Unwanted traces can now be deleted.
