### ISSUE TITLE
[Enhancement request] Ability to see what line a function was called from

### ISSUE THREAD

**Issue by caleb15** [kolofordjango/kolo#27]
I was trying to work my way through a request starting from the SQL call and backtracking, but it was difficult because kolo doesn't record call lines like you would see in a stacktrace. It would be great if I could easily navigate through the code, jumping from call to call, instead of from function to function.

**Comment by wilhelmklopp** [comment]
Thanks for opening this issue @caleb15 ! It definitely sounds like we should have strong support for the use case you're describing, so I look forward to us building this!

Could you share some more detail about how you'd expect it to work?

Currently we have these two things which are both quite hidden and unergonomic:
- jump to the place in the code where a SQL query was made (clickable above each sql query in the SQL Query virtual document)
- jump to the callsite of a given function (clickable via the "called from" code lens in the frame virtual document)

**Comment by caleb15** [comment]
Yep, thanks! That's really impressive how fast you added that. This helped me understand our login code better.

There's still some usability improvements that can be made, IMO:

* It's not immediately clear what the second line is. This is a minor quibble, because I figured it out pretty fast. I think it's all the calls that happened inside the function?
* If the second line is long you can't scroll or navigate to the right to see the end section. You have to expand your window to the left so it all fits in view. This could be a blocker if you can't expand the window enough (ex: tiny laptop screen)
* When you have the framespan vdoc focused and you click on a function in the left sidebar, the code opens up on the right side replacing the vspan. This is annoying but just a minor issue with plenty of workarounds. Workarounds: unfocus vdoc before clicking, manually go to caller, or go to caller in vdoc and then go to code from vdoc link.

Regardless, the update you made addresses my original issue so I'll close this issue :)

![image](https://user-images.githubusercontent.com/46505081/191413691-11bfbb05-dcbe-4a18-a1a8-d4f7ec05229d.png)

**Comment by wilhelmklopp** [comment]
Really appreciate your additional feedback and thoughts here @caleb15 ❤️

I'd like to rework the framespan vdoc in the near future to make it a lot more pleasant to use, so this is all super helpful!
