### ISSUE TITLE
Could not get dbFilePath when attempting to use db

### ISSUE THREAD

**Issue by yashuVI** [kolofordjango/kolo#28]
My localhost db setup is PostGres. Added Kolo as middleware. installed kolo pkg. But throwing a VScode **Error: Could not get dbFilePath when attempting to use db**

**Comment by wilhelmklopp** [comment]
@yashuVI 👋 can you spot a `.kolo` directory at the top level in your VSCode workspace? If not, you may need to set the "path to kolo directory" in your vscode settings: https://github.com/kolofordjango/kolo#path-to-kolo-directory


---

if the `.kolo` directory is at the top level, could you let me know if a `db.sqlite3` file exists in that repo and what the size of that file is?

Thanks!

**Comment by yashuVI** [comment]
Hello @Wilhelm ***@***.***>, .kolo is at the top level of my vscode workspace. Please find the whereabouts of db.sqlite3 in the attachment.
***@***.***

Thanks.
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by yashuVI** [comment]
Heyy! Setting the path in extension settings works. Thanks man. 👍

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by yashuVI** [comment]
@wilhelmklopp setting path to kolo directory worked. Thanks!

**Comment by wilhelmklopp** [comment]
Great to hear @yashuVI 😄 


If you have any feedback on Kolo as you use it, let us know!

We also have a discord: https://kolo.app/discord
