### ISSUE TITLE
Show the port number in URL's

### ISSUE THREAD

**Issue by 777GE90** [kolofordjango/kolo#31]
When Kolo captures HTTP Requests (this may apply to other scenarios too) it shows the request URL without the port number.

Example:
<img width="384" alt="image" src="https://user-images.githubusercontent.com/13543144/191997517-7bb883f7-db2c-4349-9d7d-a5c6aa02c542.png">

Here the URL is actually hitting http://127.0.0.1:5025/site-topology - it would be good to see that reflected in the URL.

**Comment by caleb15** [comment]
Agreed, If you have multiple microservices listening on different ports on your machine, this could be useful to identify which microservice is being called. Most of the time you can tell by the url, but what if the url request is just to `localhost/`?

**Comment by caleb15** [comment]
Thanks!
