### ISSUE TITLE
KeyError: 'sql'

### ISSUE THREAD

**Issue by icemac** [kolofordjango/kolo#32]
I get the following exception when using kolo:

```python
2022-09-23 15:34:02 DEBUG: Unexpected exception in default_include_frames: <kolo.filters.sql.SQLQueryFilter object at 0x10f7d3220>
Traceback (most recent call last):
  File ".../Django-4.0.7-py3.9.egg/django/db/models/query.py", line 657, in get_or_create
    return self.get(**kwargs), False
  File ".../Django-4.0.7-py3.9.egg/django/db/models/query.py", line 496, in get
    raise self.model.DoesNotExist(
rest_framework.authtoken.models.Token.DoesNotExist: Token matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../kolo-2.0.3-py3.9.egg/kolo/profiler.py", line 171, in __call__
    frame_data = frame_filter.process(
  File ".../kolo-2.0.3-py3.9.egg/kolo/filters/sql.py", line 117, in process
    sql = frame.f_locals["sql"]
KeyError: 'sql'
```

kolo: 2.0.3
Django: 4.0.7
Python: 3.9

**Comment by LilyFoote** [comment]
Hi @icemac. Can you share more information about the code that caused the `Token.DoesNotExist` exception? I've not managed to replicate this locally.

**Comment by icemac** [comment]
I think this happens when using `rest_framework.authentication.TokenAuthentication` in `settings.py`:

```python
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ]
}
```

It seems to occur in the method `authenticate_credentials` which is called during the authentication process if the user is not yet authenticated.

**Comment by LilyFoote** [comment]
@icemac Thanks for the extra information. Unfortunately I still cannot replicate. Can you extract a minimal reproducing example from your codebase and make it public?

**Comment by icemac** [comment]
@LilyFoote Sorry, I cannot do that: I do not have the time.

**Comment by wilhelmklopp** [comment]
@icemac thanks for opening this – very understandable you don't have the time to make a reproducible example.

Could you remind me which database you're using?

**Comment by icemac** [comment]
@wilhelmklopp I am using `postgres:10` via docker.
