### ISSUE TITLE
Removing requests

### ISSUE THREAD

**Issue by Real-Gecko** [kolofordjango/kolo#44]
Would be nice to have the ability to selectively remove requests from list and database:
![image](https://user-images.githubusercontent.com/2231969/206121072-65baf7e2-43a5-4b9d-8315-170d5a8c1a90.png)
On this project I deleted `.kolo/db.sqlite3` to remove old requests I did not need, because DB was ~800 MB already and I'm really not interested in requests I made month ago. If only there was a button that allowed to cleanup older requests, or requests I really don't need.

**Comment by wilhelmklopp** [comment]
We've added a button (accessible via right click/context menu) to disable individual traces or via multi select even multiple traces.

Better options to mass/bulk delete coming soon ™️

**Comment by LilyFoote** [comment]
We've added various ways to delete unwanted traces.

**Comment by Real-Gecko** [comment]
Great, thank you!
