### ISSUE TITLE
Highlight problematic SQL queries

### ISSUE THREAD

**Issue by vhtkrk** [kolofordjango/kolo#5]
The `SQL Queries` view of the VS Code extension does what it promises, but there are two things I'm missing from it that would make it even better (and my job easier):

1. Duplicate queries: If the same *exact* SQL query is called multiple times when rendering a view, it would be useful to see the duplicates somehow highlighted as being potentially problematic/having room for improvement.
2. n+1 queries: If the same SQL query is being called multiple times with only different `WHERE` clauses, it is a strong hint that there's an n+1 queries problem caused by e.g. a missing select_related or prefetch or such. Automatically highlighting these as problematic would be a neat addition as well.

**Comment by wilhelmklopp** [comment]
Thanks for opening this issue and detailing these two use cases! Completely agree and happy to say that this is already on our roadmap and we're working on it at the moment 🙌  We're actually trying to go even one step further and show you not only that you have duplicate queries, but exactly where in your code the first/second/etc. duplicate query originated.

We're hoping to have this ready within the next couple of weeks 🔜

**Comment by Scalamoosh** [comment]
+1 for highlighting duplicate queries.

**Comment by wilhelmklopp** [comment]
👋  Hey folks!

We just released version 1.10.0 of the VSCode extension which highlights duplicate queries, like so:

  <img src="https://user-images.githubusercontent.com/7718702/149631547-b57a0ed3-db96-4ebc-9e89-d7e7c0ca2e38.png" width=500px>

You can copy and search for the `sql_` id to find the corresponding duplications of the SQL query.

We're looking into how to best highlight n+1 queries as well, will post here again when we have something to share 😃

**Comment by ddahan** [comment]
> We're actually trying to go even one step further and show you not only that you have duplicate queries, but exactly where in your code the first/second/etc. duplicate query originated.

This would be a killer feature! Even with django debug toolbar similar queries warning, I often struggled to find where it came from.

**Comment by wilhelmklopp** [comment]
> This would be a killer feature! Even with django debug toolbar similar queries warning, I often struggled to find where it came from.

@ddahan We've actually got this part live in Kolo already now 😁 At the top of any query, you'll see a link to where in your code the query originated:

<img width=500 src="https://user-images.githubusercontent.com/7718702/209388355-93deb441-ccca-45d2-8173-e3a687b41e6c.png">

Curious to hear what you think!
