### ISSUE TITLE
Confusing error message when Kolo can't write to `KOLO_PATH`

### ISSUE THREAD

**Issue by lewiseason** [kolofordjango/kolo#50]
First of all, loving your work! ❤️

If Kolo can't write to `.kolo` (or wherever your `KOLO_PATH` is), Django exits with this message:

> Error: You don't have permission to access that port.

I came across this in Docker, because while my code is mounted inside the container, it doesn't have write access. I can obviously account for this, but it took me a while to figure out what the problem was. Maybe Kolo could detect this and log something before Django exits to give users a hint.

Thanks!

**Comment by LilyFoote** [comment]
Hi @lewiseason. I think I've fixed this in `2.6.1`. Let me know if it doesn't work for you.

**Comment by lewiseason** [comment]
Looks good to me, thanks Lily!
