### ISSUE TITLE
Kolo constantly triggers Vue HMR

### ISSUE THREAD

**Issue by lewiseason** [kolofordjango/kolo#55]
Hello again gang,

When I have Kolo enabled, my Vue app constantly detects a change and recompiles. Presumably Kolo is touching my Vue components or some other files that Vue HMR is watching and setting it off. Is that a behaviour of Kolo, and if so, is there a way I can turn it off or opt certain paths out?

**Comment by lewiseason** [comment]
Aha, I assumed that Vue was only watching my components, but it is not. My bad - thanks for the quick response!

**Comment by wilhelmklopp** [comment]
@lewiseason curious if you found the setting to change this in Vue? Perhaps we can add a note to our docs to give folks a heads up

I saw something similar previously with watchman and had to tell it to ignore the `.kolo` directory: https://facebook.github.io/watchman/docs/config.html#ignore_dirs

**Comment by lewiseason** [comment]
I haven't yet @wilhelmklopp I'm afraid. I'm temporarily disabling Kolo for now while I work on this feature. If I come back to it later, I can leave a comment here to help others!

**Comment by wilhelmklopp** [comment]
@lewiseason I had a brief look around and stumbled upon this: https://stackoverflow.com/a/56853687/2162900

**Comment by lewiseason** [comment]
That doesn't work for me unfortunately, although we're using an LTS version of Vue (2.7) which is pretty old by javascript standards so I expect that's why
