### ISSUE TITLE
Installing test generation dependencies hint

### ISSUE THREAD

**Issue by EduardRosert** [kolofordjango/kolo#58]
Hi,

in the kolo VSCode extension, if I right click on a request and select "generate test" I get the error message that test_generation dependencies are not installed:
```zsh
% kolo generate-test trc_01H1Y5D8AEW5S0E7P2CF7XW183 >> test_from_kolo.py
Error: Test generation dependencies are not installed.

Run `pip install kolo[test_generation]` to install them.
```
However the proposed command ``pip install kolo[test_generation]`` fails with zsh under macOS:

```zsh
% pip install kolo[test_generation]  
zsh: no matches found: kolo[test_generation]
```

Changing the hint to:
```text
Run

    pip install 'kolo[test_generation]'    # Unix/macOS
or
    pip install "kolo[test_generation]"    # Windows

to install them.
```
should make sure that the command works on every system independent of the shell used.

**Comment by LilyFoote** [comment]
This will be fixed in the next release.
