### ISSUE TITLE
Can't open admin sql query 

### ISSUE THREAD

**Issue by shivambalwani0704** [kolofordjango/kolo#59]
Trying to open SQL query for a admin API it is not opening in text editor in VS code

**Comment by wilhelmklopp** [comment]
@shivambalwani0704 👋 hey! are there any errors that show up when you do this?

**Comment by wilhelmklopp** [comment]
@shivambalwani0704 we're recently made some improvements here, so I believe this should work now! Please let me know if you're still experiencing issues :)
