### ISSUE TITLE
Replay request (or copy as cURL)

### ISSUE THREAD

**Issue by vhtkrk** [kolofordjango/kolo#6]
When I'm looking at the requests logged by the middleware and then shown in the VS Code extension, it would be handy to be able to replay a request straight from VS Code with the press of a button. Or if making the request is somehow out of the question, a passable alternative would be to be able to copy the request as a `curl` command to the clipboard (or a new buffer), much like the network inspector of most browsers allows you to do.

**Comment by wilhelmklopp** [comment]
Great idea 💯 

I wonder how hard it would be to implement a replay functionality, I'll take a look at that. In theory, we already have all the information: host, path, headers, etc. so maybe it shouldn't be too hard! (famous last words)

One other thought I had: Internally we primarily use Kolo when developing our django app [Simple Poll](http://simplepoll.rocks/). And Simple Poll primarily consumes webhook events from Slack/Stripe. Their webhook systems have a time-based signing mechanism which in part is intended to prevent replay attacks and would also mean this replay feature wouldn't work or would only work in a limited way for those requests. But I see no reason why Kolo couldn't learn to be smart about specific webhook systems and make the replay feature work even when requests need some kind of signing. That could be pretty interesting.

But anyway! I'll report back here when I've had a chance to play around with implementing this 😄

**Comment by wilhelmklopp** [comment]
I just shipped this with the latest version of the VSCode extension:

https://user-images.githubusercontent.com/7718702/135449686-815bc247-4cb3-4fb4-8526-8a67ed6fd743.mov

Let me know if this works as expected for you 😄

**Comment by vhtkrk** [comment]
Seems to work as advertised, thank you! :)
