### ISSUE TITLE
Could not get dbFilePath when attempting to use db

### ISSUE THREAD

**Issue by slavaOtonomo** [kolofordjango/kolo#60]
`Could not get dbFilePath when attempting to use db` error. Extension starts with default config but doesn't work.

**Comment by wilhelmklopp** [comment]
@slavaOtonomo 👋 I feel like I've seen this error in the past when the kolo vscode extension struggles to find the kolo database file.

Is the `.kolo` directory at the root of your open vscode workspace? If it's not and it's in a nested folder, you will likely have to set this setting: https://docs.kolo.app/en/latest/vscode-config.html#path-to-kolo-directory
