### ISSUE TITLE
An error occured while running django app

### ISSUE THREAD

**Issue by Dev-mininos** [kolofordjango/kolo#61]
kolo version:2.11.0
django version:4.2.3
python version: 3.10.11
While running a django app with kolo vscode, i encountered this error:
`thread '<unnamed>' panicked at 'Serde json could not load json value dumped by python.: Error("expected value", line: 1, column: 8672)', src\lib.rs:228:14
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace`
is there any steps to fix it?

**Comment by wilhelmklopp** [comment]
@Dev-mininos 👋  if you put `use_rust = False` at the top of your `.kolo/config.toml`, does it work then?

https://docs.kolo.app/en/latest/config.html

**Comment by LilyFoote** [comment]
@Dev-mininos Please re-open this if you see something similar again.
