### ISSUE TITLE
Error when trying to open a db query

### ISSUE THREAD

**Issue by DentaCool** [kolofordjango/kolo#64]
VSCODE:
"Invalid query argument. Extected string, instead got object"

I also added the log of the object itself to the throw via vim:

"Invalid query argument. Extected string, instead got object: null"

UPD: 
FRAME: file 'python3.9/site-packages/django/db/models/sql/compiler.py', line 1161, code execute_sql>

```
def execute_sql(self, result_type=MULTI, chunked_fetch=False, chunk_size=GET_ITERATOR_CHUNK_SIZE):
        result_type = result_type or NO_RESULTS
        try:
            sql, params = self.as_sql()
            if not sql:
                raise EmptyResultSet
        except EmptyResultSet:
            if result_type == MULTI:
                return iter([])
            else:
                return
 ```
UPD 2:

from psqlextra.query import PostgresQuerySet

**Comment by LilyFoote** [comment]
Hard to say for sure without looking closely myself, but I wonder if we're just recording the query as `null` because we can't introspect it as something more useful.

**Comment by DentaCool** [comment]
```python
class SQLQueryFilter:
  def process(
          self,
          frame: types.FrameType,
          event: str,
          arg: Any,
          call_frames: List[Tuple[types.FrameType, str]],
      ):
      # ...
        try:
            sql = frame.f_locals["sql"]
            params = frame.f_locals["params"]
        except KeyError:
            query_template = None
            query = None
        # ...
```


django/db/models/sql/compiler.py
```python
def execute_sql():
        try:
            sql, params = self.as_sql()
            if not sql:
                raise EmptyResultSet
        except EmptyResultSet:
            if result_type == MULTI:
                return iter([])
```
this function fails with EmptyResultSet and returns iter([]). Thus 
```python
sql = frame.f_locals["sql"]
params = frame.f_locals["params"]
```

also fails with a KeyError and we will get 
```json
{
    "database": "postgres",
    "query": null,
    "query_template": null,
    "query_data": "<list_iterator object at 0x00B99F28>",
    "type": "end_sql_query"
}
```

At the moment, I'm just hardcoded fake query_template, query and query_data at KeyError. 
I will try to find more information and a solution as soon as I have time

**Comment by LilyFoote** [comment]
That's very interesting! Do you know which queryset in your code ends up with the `EmptyResultSet` exception?

**Comment by LilyFoote** [comment]
Thanks! I'll look into that properly tomorrow.

**Comment by LilyFoote** [comment]
Looks like this is caused by `Model.objects.none()` or similar. In that case, there isn't a `query` to record, so Kolo stores `null` instead. I think this is something we need to handle better in VSCode.

**Comment by LilyFoote** [comment]
@wilhelmklopp Actually, we could just ignore this case on the python side. I'm not sure if it's valuable to display empty queries like this.

**Comment by wilhelmklopp** [comment]
👋 @DentaCool the latest version of the VSCode extension (2.8.1) includes the fix for this :)
