### ISSUE TITLE
Why do some of the views open in a split view?

### ISSUE THREAD

**Issue by kevinrenskers** [kolofordjango/kolo#68]
When you click on a frame or a SQL query, the information opens in a new tab in your active editor. But when you click on request or response, it opens in a split view on the right side. I find this a bit annoying, and would like to be able to configure this behavior.

**Comment by wilhelmklopp** [comment]
@kevinrenskers I'm looking in this a bit today. Did you have any thoughts on what kind of configuration option you'd like to see here?

I'm currently thinking of providing just one on/off setting which is essentially "never open things in a split view". Is that more or less what you were looking for?

**Comment by kevinrenskers** [comment]
Yeah, basically. I just never want stuff to open in a split view, and think the default options should be to not do that.

**Comment by wilhelmklopp** [comment]
@kevinrenskers thanks!

I can definitely see not wanting a split view when clicking on various things in the kolo sidebar (like a frame, or request, or sql query information).

But what about when clicking on a node in the visualisation or on a code annotation within code? Would you want those to open in a split view or also prefer no split view? Showing both in the video:



https://github.com/kolofordjango/kolo/assets/7718702/9e1c362d-187b-4553-8f31-e62740c80c08

**Comment by kevinrenskers** [comment]
I guess that would make sense, although personally I just get lost with what tab is in what split view and I end up being annoyed haha.

But the split view usage should definitely be limited to those kinds of cases where it really makes sense. Thanks!
