### ISSUE TITLE
Support other task queues than Celery

### ISSUE THREAD

**Issue by vhtkrk** [kolofordjango/kolo#7]
Celery is the classical choice for a task queue in Python/Django land, but it is a bit on the heavy side and quite frankly an overkill for many projects that just need a simple task queue without the kitchen sink included.

For that, our project has been using [huey](https://huey.readthedocs.io/en/latest/) with its included [huey.contrib.djhuey](https://huey.readthedocs.io/en/latest/contrib.html#django) Django integration. There also exists a [django-huey](https://github.com/gaiacoop/django-huey) which I've understood is somewhat popular, and adds some more options like multiple task queues on top of what is still mostly `huey.contrib.djhuey`. We also considered [Django Q](https://github.com/Koed00/django-q) as an alternative that seemed very polished but I don't have personal experience with that.

Personally I would benefit most from a `huey.contrib.djhuey` integration, but I like to think the others would be useful for someone else too.

**Comment by simkimsia** [comment]
Adding another vote for huey 

I started using huey in greenfield projects as default instead of celery
