### ISSUE TITLE
Error: no module named asgiref

### ISSUE THREAD

**Issue by corentinbettiol** [kolofordjango/kolo#71]
Here's the error I got after adding Kolo to one of my projects in order to try it:
```sh
  File "/home/me/projects/project-name/.venv/lib/python3.9/site-packages/kolo/middleware.py", line 9, in <module>
    from asgiref.sync import iscoroutinefunction
ModuleNotFoundError: No module named 'asgiref'
```

**Comment by LilyFoote** [comment]
In that case, try installing `asgiref`.

**Comment by corentinbettiol** [comment]
Yes I added `asgiref` manually and now it's still not working but for other reasons (see #72) :)

You may want to add it to the requirements of the kolo package since people may want to use it with old django projects :)

**Comment by LilyFoote** [comment]
I've added the dependency. It'll be in the next release.

**Comment by corentinbettiol** [comment]
Thanks!
