### ISSUE TITLE
Need help setting up kolo in codebase

### ISSUE THREAD

**Issue by g-kartik** [kolofordjango/kolo#76]
I am using docker for local development. I have followed the instructions from the `README` file and have successfully managed to obtain the traces. However my main intent to use Kolo for generating tests and I am unable to do it. I am facing the following issue.

![image](https://github.com/kolofordjango/kolo/assets/83916067/ab28c942-30c8-4872-93a5-a923b00a42d3)

## Reference Images:
![image](https://github.com/kolofordjango/kolo/assets/83916067/79d89915-2640-4798-b03b-0b68c6e852f5)
![image](https://github.com/kolofordjango/kolo/assets/83916067/1bbe4e1d-4ecd-4419-af0e-28f5b2d66258)

**Comment by wilhelmklopp** [comment]
@g-kartik sorry, looks like I totally missed this!

Looking at your first screenshot, I believe it _should_ work if you `cd` into the `backend` directory and then run the command again.

when in `backend`, running `kolo trace list` will also show all your recent traces

**Comment by wilhelmklopp** [comment]
@g-kartik let us know if you're still looking for some help here :) or if you were able to successfully generate some tests, if you have any feedback on the test generation 🤘 Thanks!
