### ISSUE TITLE
Kolo doesn't seem to capture any information (No execution nodes captured)

### ISSUE THREAD

**Issue by kwint** [kolofordjango/kolo#78]
Not sure what I am doing wrong here

Installed kojo as a middleware, and it is clearly doing something.

![image](https://github.com/kolofordjango/kolo/assets/7907280/d70cd292-d9c8-44cb-b90d-43f7e70e528e)

Could it be because we use django-channels?

**Comment by LilyFoote** [comment]
Hey @kwint! Are you able to view the raw trace? If you right click one of these traces you should see a menu with an `Open raw trace` option. It would be useful to see the contents of that to narrow down the problem.

If you're able to share a minimal code sample that shows the bug, that would be amazing too.

**Comment by kwint** [comment]
Thanks for looking in to this @LilyFoote 
```
{
  "command_line_args": [
    "manage.py",
    "runserver",
    "0.0.0.0:8888"
  ],
  "current_commit_sha": "463c2b03c79ffc6d0bb6b199fa26630f868fa432",
  "frames": {},
  "frames_of_interest": [],
  "main_thread_id": 5349,
  "meta": {
    "version": "2.17.0",
    "source": "kolo.middleware.KoloMiddleware",
    "use_frame_boundaries": true
  },
  "timestamp": 1706111972.2848043,
  "trace_id": "trc_01HMY35CXW7X43EB0FF2QGHRJJ"
}
```

This is the raw trace. All of them look the same.

tbh I have no clue where to start with making a minimal code sample, but i'll give it a shot

**Comment by kwint** [comment]
My db is listening to a non default port, but I doubt that is it?

**Comment by kwint** [comment]
Playing a little bit more around with gave me this captured "thing":

![image](https://github.com/kolofordjango/kolo/assets/7907280/9718cf52-6b2a-4d1a-8c82-a6e653aeba29)

The log opens and shows me this json:
```
# [mHTTP GET /static/admin/css/widgets.css 200 [0.05, 127.0.0.1:41676][0m
{
  "msg": "\u001b[mHTTP %(method)s %(path)s %(status)s [%(time_taken).2f, %(client)s]\u001b[0m",
  "args": [
    {
      "path": "/static/admin/css/widgets.css",
      "status": 200,
      "method": "GET",
      "client": "127.0.0.1:41676",
      "time_taken": 0.04927849769592285,
      "size": 11921
    }
  ],
  "extra": null,
  "level": "INFO"
}


```

**Comment by ahmedyasserays** [comment]
I have the same issue

I noticed very high load on my device and htop was giving me more than 200% cpu usage in vs code so i killed the process 

this happened after running some automation on my local machine which caused high load on the server and many query executions

although it's not kolo's fault but now i'm unable to make anything work again

i tried reinstalling the python package or the vs code extension but nothing worked

**Comment by ahmedyasserays** [comment]
note that it's working fine with another project in the same machine

**Comment by ahmedyasserays** [comment]
@LilyFoote  I had the same issue but i managed to fixed it
from the documentation https://docs.kolo.app/en/latest/tutorial.html#configuration
we should put the middleware in the top of all other middlewares

**Comment by LilyFoote** [comment]
I think we have a solution then. @kwint feel free to re-open if it doesn't work for you.
