### ISSUE TITLE
Changelog dates are off by one year, broken Edit on Github docs link

### ISSUE THREAD

**Issue by Xronophobe** [kolofordjango/kolo#81]
The dates of the releases are off by one year for v2.20.1, v2.20.0 and v2.19.0:
 https://docs.kolo.app/en/latest/python-changelog.html. 

I figured I would just edit it and create a PR, but the `Edit on GitHub` is broken. It's set to https://github.com/kloppindustries/kolo/blob/main/docs/python-changelog.md which does not exist any longer, and neither searching the docs' source in your GitHub repo, neither the guess-work (changing `kloppindustries` to `kolofordjango`) worked.

Sorry for the ugly budling of two issues in one ticket, I just didn't want to spam with two for such minor things.

**Comment by LilyFoote** [comment]
Thanks for this, I'll get these fixed!

**Comment by LilyFoote** [comment]
I've fixed the changelog dates.

Fixing the "Edit on GitHub" button is not so straightforward - since our docs source is private, we should disable the button, but that's a bit more of a faff than I'd hoped: https://docs.readthedocs.io/en/stable/guides/remove-edit-buttons.html
