### ISSUE TITLE
Email Link , marked fishing link by norton

### ISSUE THREAD

**Issue by PronoyJoy** [kolofordjango/kolo#82]
Tried to give email and recieved a link but Norton Antivirus marked the link as fishing link

**Comment by wilhelmklopp** [comment]
hey @PronoyJoy 👋 – thanks for the report!

Do you have a screenshot by any chance, we can look into filing a report with norton antivirus. 

I just checked this and it seems to be all fine there: https://safeweb.norton.com/report?url=kolo.app

<img width="938" alt="image" src="https://github.com/kolofordjango/kolo/assets/7718702/104cad9f-4a18-4b1e-877a-cd7b46bdd30f">

also curious what operating system are you using?
