### ISSUE TITLE
Error in logs when viewing Django admin pages

### ISSUE THREAD

**Issue by jlicht** [kolofordjango/kolo#84]
With Django 5.0.4 and kolo 2.23.0, this error occurs when viewing any page in the admin console:

`WARNING Unexpected exception in Rust.
    co_filename: /usr/local/lib/python3.10/site-packages/django/template/base.py
    co_name: _render
    event: return
    frame locals: {'self': <Template template_string="{% autoescape off %}...">, 'context': [{'True': True, 'False': False, 'None': None}, {'catalog': {}, 'formats': {'DATE_FORMAT': 'N j, Y', 'DATETIME_FORMAT': 'M j, Y g:i:s A e', 'TIME_FORMAT': 'P', 'YEAR_MONTH_FORMAT': 'F Y', 'MONTH_DAY_FORMAT': 'F j', 'SHORT_DATE_FORMAT': 'm/d/Y', 'SHORT_DATETIME_FORMAT': 'm/d/Y P', 'FIRST_DAY_OF_WEEK': 0, 'DECIMAL_SEPARATOR': '.', 'THOUSAND_SEPARATOR': ',', 'NUMBER_GROUPING': 3, 'DATE_INPUT_FORMATS': ['%m/%d/%Y', '%Y-%m-%d', '%m%d%Y'], 'TIME_INPUT_FORMATS': ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M'], 'DATETIME_INPUT_FORMATS': ['%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M:%S.%f', '%Y-%m-%d %H:%M', '%m/%d/%Y %H:%M:%S', '%m/%d/%Y %H:%M:%S.%f', '%m/%d/%Y %H:%M', '%m/%d/%y %H:%M:%S', '%m/%d/%y %H:%M:%S.%f', '%m/%d/%y %H:%M', '%Y-%m-%d']}, 'plural': None, 'catalog_str': None, 'formats_str': '{\n    "DATETIME_FORMAT": "M j, Y g:i:s A e",\n    "DATETIME_INPUT_FORMATS": [\n      "%Y-%m-%d %H:%M:%S",\n      "%Y-%m-%d %H:%M:%S.%f",\n      "%Y-%m-%d %H:%M",\n      "%m/%d/%Y %H:%M:%S",\n      "%m/%d/%Y %H:%M:%S.%f",\n      "%m/%d/%Y %H:%M",\n      "%m/%d/%y %H:%M:%S",\n      "%m/%d/%y %H:%M:%S.%f",\n      "%m/%d/%y %H:%M",\n      "%Y-%m-%d"\n    ],\n    "DATE_FORMAT": "N j, Y",\n    "DATE_INPUT_FORMATS": [\n      "%m/%d/%Y",\n      "%Y-%m-%d",\n      "%m%d%Y"\n    ],\n    "DECIMAL_SEPARATOR": ".",\n    "FIRST_DAY_OF_WEEK": 0,\n    "MONTH_DAY_FORMAT": "F j",\n    "NUMBER_GROUPING": 3,\n    "SHORT_DATETIME_FORMAT": "m/d/Y P",\n    "SHORT_DATE_FORMAT": "m/d/Y",\n    "THOUSAND_SEPARATOR": ",",\n    "TIME_FORMAT": "P",\n    "TIME_INPUT_FORMATS": [\n      "%H:%M:%S",\n      "%H:%M:%S.%f",\n      "%H:%M"\n    ],\n    "YEAR_MONTH_FORMAT": "F Y"\n  }'}]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/kolo/filters/django.py", line 96, in process_django_template
    "template": frame.f_locals["self"].name + "",
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`

**Comment by LilyFoote** [comment]
Thanks for the report, I'll take a look!
