### ISSUE TITLE
License and terms?

### ISSUE THREAD

**Issue by sknutsonsf** [kolofordjango/kolo#89]
I love the idea of Kolo.  However, I can't use it yet

What is the plan to either release it as open source or provide some license and commercial terms?

I am not willing to incorporate software that could be uploading traces or source code without notice.  Too many issues of "software supply chain" security attacks.  My previous employer refused to allow any open source to be used for that reason.

**Comment by danielgavrilov** [comment]
Hi, we totally get that. Data inside your traces may contain private keys and proprietary code, so we treat it as sensitive data and never upload your traces (or part of them) to any remote servers.

It is possible to upload traces to share them with others, like to debug something with a colleague for example, but that's an [explicit command in the Kolo CLI](https://docs.kolo.app/en/latest/reference/cli.html#kolo-trace-upload) and unlikely to happen unintentionally.

We also just released our [terms of service](https://kolo.app/terms-of-service) and [privacy policy](https://kolo.app/privacy-policy).

Does that help?

**Comment by wilhelmklopp** [comment]
@sknutsonsf closing this as I think it's resolved, but please let us know if there's something else we can help with :)
