### ISSUE TITLE
Unintended unicode escape in variable projectFolder

### ISSUE THREAD

**Issue by briandarnell** [kolofordjango/kolo#90]
Hi,

I'm using Kolo 2.33.3 in a venv on Windows.  I have come across an issue of a blank page when viewing http://127.0.0.1:8000/_kolo/

In the browser console I was able to see `SyntaxError: Invalid Unicode escape sequence (at _kolo/:25:60)`

On my set-up, that line is:

`"projectFolder": "C:\Users\Brian\Documents\apps\unity",`

I believe the \u is treated as a unicode escape. I was able to resolve this by amending /kolo.web/home.py line 21, changing it from:

`project_folder = kolo_dir.parent`

To:

`project_folder = str(kolo_dir.parent).replace("\\", "\\\\")  # Escape backslashes`

Best regards,
Brian

**Comment by danielgavrilov** [comment]
Hey @briandarnell, thanks so much for the report and for looking into this! We should have a fix in the new release coming sometime today.

Thanks for trying out Kolo, and if you have any more feedback, please feel free to share.
