### ISSUE TITLE
Missing folder /kolo/web/static in 2.33.7

### ISSUE THREAD

**Issue by briandarnell** [kolofordjango/kolo#93]
Hi,

When upgrade from Kolo 2.33.6 to 2.33.7 in a venv on Windows, I have come across an issue of a blank page when viewing http://127.0.0.1:8000/_kolo/

The Chrome DevTools console shows:
GET http://127.0.0.1:8000/_kolo/static/spa/main.css net::ERR_ABORTED 404 (Not Found)
GET http://127.0.0.1:8000/_kolo/static/spa/main.js net::ERR_ABORTED 404 (Not Found)

Comparing the versions it appears that the folder /kolo/web/static is missing from the 2.33.7 version.

I was able to resolve it temporarily by copying across the static folder from 2.33.6 but of course I might encounter some incompatibilities.

Best regards,

Brian

**Comment by wilhelmklopp** [comment]
@briandarnell thanks for the report, much appreciated 🫡  – looking into it now

**Comment by wilhelmklopp** [comment]
This has been fixed in v2.33.8
