### ISSUE TITLE
Dependency python-magic-bin seems to be unmaintained

### ISSUE THREAD

**Issue by satya-waylit** [kolofordjango/kolo#95]
I ran into an error trying to resolve `kolo` using `uv`. I'm using Python 3.12. Seems `python-magic-bin` hasn't seen an update since 2017. The package `python-magic` seems to be maintained. Any chance to switch to a maintained dependency?

```
× No solution found when resolving dependencies:
0.719   ╰─▶ Because python-magic-bin==0.4.14 has no wheels with a matching platform
0.719       tag and you require python-magic-bin==0.4.14, we can conclude that your
0.719       requirements are unsatisfiable.
```

**Comment by wilhelmklopp** [comment]
👋 Hey @satya-waylit 

Thanks for the report, I've looked into it a bit and looks like we install `python-magic-bin` on Windows to make sure `mocket` works. Just to confirm, are you on Windows? And could you run `uv tree` and paste the result in this thread?

Ultimately, it looks like when this PR gets merged, we'll be able to remove our dependency on `python-magic-bin`: https://github.com/ahupp/python-magic/pull/294

But until then, I'm not sure if there is an easy resolution. Are you able to run with WSL as opposed to with windows directly?

**Comment by satya-waylit** [comment]
@wilhelmklopp Indeed, using Windows. I was using WSL for the longest, but WSL seems to getting very unstable these days. May be that's why I ran into this issue. Will wait for the upstream fix.

**Comment by satya-waylit** [comment]
I checked mocket's code and it seems magic should be an optional dependency. https://github.com/mindflayer/python-mocket/issues/254

**Comment by ddelange** [comment]
I see that kolo specifies `python-magic-bin ; platform_system == 'Windows'`.

My [PR](https://github.com/ahupp/python-magic/pull/294) on python-magic builds `win32` and `win_amd64` wheels, just like python-magic-bin does.

The error in the issue description implies that the user is on platform_system Windows, but no wheels available for his distribution according to uv.

Maybe ARM64 Windows? In that case, my PR won't solve OP's issue.

**Comment by satya-waylit** [comment]
amd64 in my case

**Comment by ddelange** [comment]
then you should be covered :thinking: 

can you post the output here of the following direct reference install of python-magic-bin?
```
pip install --force-reinstall https://files.pythonhosted.org/packages/07/c2/094e3d62b906d952537196603a23aec4bcd7c6126bf80eb14e6f9f4be3a2/python_magic_bin-0.4.14-py2.py3-none-win_amd64.whl
```

**Comment by ddelange** [comment]
and also the output of

```
python -c 'from packaging.markers import default_environment; print(default_environment())'
```

**Comment by satya-waylit** [comment]
@wilhelmklopp The mocket author has switch to puremagic from python-magic in the newest version. Hopefully that'll solve the problem.

**Comment by wilhelmklopp** [comment]
python-magic-bin dropped as a dependency in kolo as of v2.33.9 – nice work on getting this in front of the right people @satya-waylit
